version: "3.3"

services:
    frontend:
        build: frontend
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
        depends_on:
            - backend
        env_file: .env

    db:
        image: postgres
        ports:
            - "5432:5432"
        restart: always

        volumes:
            - ./db:/var/lib/postgresql/data/
        healthcheck:
            test: ["CMD", "sh", "-c", "pg_isready -U $$POSTGRES_USER -h $$(hostname -i)"]
            interval: 5s
            timeout: 15s
            retries: 5
        env_file: .env

    backend:
        build: backend
        ports:
            - "3001:3000"
        volumes:
            - ./backend:/app
        depends_on:
            db:
                condition: service_healthy
        env_file: .env